### PR TITLE
[TIC4001-F18-1] Librarian

### PR DESCRIPTION
**Pull request by badassengineer**

### CODE REVIEW

**Comment by badassengineer** [comment]
This is the initial setup of our simple program called Librarian. 

Librarian is a book keeping CLI program that tracks the availability of the books in the library file. Some of the key features that the user may do are the following:

- search
- borrow
- return
- reserve

**Comment by damithc** [comment]
@badassengineer the Github organization name is not as expected. It should be `AY2223S1-TIC4001-F18-1`

**Comment by damithc** [comment]
@badassengineer I'm closing this PR for the time being. Please reopen the PR after renaming the organization correctly.

**Comment by badassengineer** [comment]
Sorry for the naming error. I have renamed the organization to AY2223S1-TIC4001-F18-1. However, I don't think that I have the rights to reopen PR as the "Reopen pull requesr" button is not shown. 

Can I just resend another PR?

**Pull request closed without merging**
